config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  get    '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users
  resources :posts, except: [:index]
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :relationships, only: [:create, :destroy]
  resources :posts do
    resources :comments, only: [:create]
  end
  resources :posts do
    resources :likes, only: [:create]
    member do
      get :likes
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  VALID_EMAIL_REGEX = URI::MailTo::EMAIL_REGEXP

  extend FriendlyId
  friendly_id :username, use: :slugged

  def should_generate_new_friendly_id?
    username_changed?
  end

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :active_relationships, class_name:  "Relationship",
                                  foreign_key: "follower_id",
                                  dependent:   :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :passive_relationships, class_name:  "Relationship",
                                   foreign_key: "followed_id",
                                   dependent:   :destroy
  has_many :followers, through: :passive_relationships, source: :follower

  before_save { email.downcase! }

  validates :name, presence: true, length: { maximum: 25 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX }, uniqueness: true
  validates :username, presence: true, length: { maximum: 20 },
                       uniqueness: true
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
  has_secure_password

  def self.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def follow(other_user)
    following << other_user unless self == other_user
  end

  def unfollow(other_user)
    following.delete(other_user)
  end

  def following?(other_user)
    following.include?(other_user)
  end


  def feed
    following_ids = "SELECT followed_id FROM relationships WHERE follower_id = :user_id"
    Post.where("user_id IN (#{following_ids})", user_id: id).includes(:user, image_attachment: :blob)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :destroy, :followers, :following, :edit,
                                  :update, :destroy]
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy,
                                        :followers, :following]
  before_action :correct_user,   only: [:edit, :update, :destroy]

  def index
    @users = User.paginate(page: params[:page], per_page: 15)
  end

  def show
    @posts = @user.posts
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      reset_session
      log_in @user
      flash[:success] = "Welcome to Instagram!"
      redirect_to @user
    else
      render 'new', status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:success] = "Profile successfully updated"
      redirect_to @user
    else
      render 'edit', status: :unprocessable_entity
    end
  end

  def destroy
    @user.delete
    log_out
    flash[:success] = "Account successfully deleted"
    redirect_to root_url, status: :see_other
  end

  def followers
    @title = "Followers"
    @users = @user.followers.paginate(page: params[:page], per_page: 15)
    render 'index'
  end

  def following
    @title = "Following"
    @users = @user.following.paginate(page: params[:page], per_page: 15)
    render 'index'
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :username, :password)
  end

  def set_user
    @user = User.friendly.find(params[:id])
  end

  def correct_user
    redirect_to(root_url) unless current_user?(@user)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_follow.html.erb
<%= form_with(model: current_user.active_relationships.build, local: true) do |f| %>
  <%= hidden_field_tag :followed_id, object.id %>
  <%= f.submit "Follow", class: "btn btn-primary #{style}" %>
<% end %>

app/views/users/_pagination.html.erb
<% if @users.count > 15 %>
  <div class="apple_pagination bg-light">
    <%= will_paginate @users, :container => false %>
  </div>
<% end %>

app/views/users/_relationship_form.html.erb
<span id="follow_form">
<% if current_user.following?(object) %>
  <%= render 'users/unfollow', object: object, style: style  %>
<% else %>
  <%= render 'users/follow', object: object, style: style  %>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_with(model: current_user.active_relationships.find_by(followed_id: object.id),
             html: { method: :delete }, local: true) do |f| %>
  <%= f.submit "Unfollow", class: "btn btn-secondary #{style}" %>
<% end %>

app/views/users/_user.html.erb
<li class="mb-5">
  <p><%= fa_icon("user-circle", class: "fa-5x")%>
    <p class="user text-muted">
      <%= user.name %>
    </p>
    <p class="fw-bold user">
      <%= link_to user.username, user %>
    </p>
    <%= render 'users/relationship_form', { object: user, style: "follow-button" } %>
  </p>
</li>

app/views/users/edit.html.erb
<% provide(:subtitle, "Edit profile") %>

<div class="form-card">
  <div class="card">
    <div class="card-body">
      <h3 class="mb-3 mt-2 text-center">
        <svg xmlns="http://www.w3.org/2000/svg" width="60" height="60" fill="currentColor" class="bi bi-person-circle" viewBox="0 0 16 16">
          <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z"/>
          <path fill-rule="evenodd" d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z"/>
        </svg>
      </h3>

      <%= form_with(model: @user, local: true) do |f| %>

        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control" %>

        <%= f.label :username %>
        <%= f.text_field :username, class: "form-control" %>

        <%= f.label :email %>
        <%= f.email_field :email, class: "form-control" %>

        <%= f.label :password %>
        <%= f.password_field :password, class: "form-control" %>

        <%= f.submit "Update my profile", class: "w-100 btn btn-primary" %>

        <%= render 'shared/error_messages', object: f.object %>
      <% end %>

      <%= link_to "Delete my account", @user,
                   data: { "turbo-method": :delete, "turbo_confirm": 'Are you sure?' },
                   class: "w-100 btn btn-danger" %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="users-card">
  <div class="card">
    <%= render 'pagination' %>
    <div class="card-body">
      <% if @title %>
      <h5 class="relationship-title text-center mb-3"><%= @title %>
        <%= fa_icon("user-circle") %> <%= link_to @user.username, @user %>
        <hr class="divider">
      </h5>
      <% end %>
      <% if @users.any? %>
        <ul class="users">
          <%= render @users %>
        </ul>
      <% end %>
    </div>
    <%= render 'pagination' %>
  </div>
</div>

app/views/users/new.html.erb
<% provide(:subtitle, "Sign up") %>

<div class="form-card">
  <div class="card">
    <div class="card-body text-center">
      <h3 class="mb-3 mt-2 logo">Instagram</h3>
      <p class="mb-2 fw-bold text-muted">Sign up to see photos and videos from your friends</p>

      <%= form_with(model: @user, local: true) do |f| %>

        <%= f.email_field :email, placeholder: "Email address", class: "form-control" %>

        <%= f.text_field :name, placeholder: "Full name", class: "form-control" %>

        <%= f.text_field :username, placeholder: "Username", class: "form-control" %>

        <%= f.password_field :password, placeholder: "Password",  class: "form-control" %>

        <%= f.submit "Create my account", class: "w-100 btn btn-primary" %>

        <%= render 'shared/error_messages', object: f.object %>
      <% end %>

      <p class="fine-print text-muted">By signing up, you agree to our Terms. Learn how we collect,
        use and share your data in our Data Policy, and how we use cookies and similar technology
        in our Cookie Policy.
      </p>
    </div>
  </div>
</div>

<div class="form-card-sub">
  <div class="card">
    <div class="card-body text-center">
        <p class="mt-2 mb-2">Have an account? <%= link_to "Log in", login_path %></p>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:subtitle, "#{@user.name} (@#{@user.username})") %>

<section class="py-5 text-center container">
  <div class="row py-lg-5">
    <h1 class="fw-light">
      <svg xmlns="http://www.w3.org/2000/svg" width="60" height="60" fill="currentColor" class="bi bi-person-circle" viewBox="0 0 16 16">
        <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z"/>
        <path fill-rule="evenodd" d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z"/>
      </svg>
      <span><%= @user.username %></span>
      <span class="relationship-btn">
        <% if current_user?(@user) %>
          <%= link_to "Edit profile", edit_user_path(@user), class: "btn btn-outline-dark" %>
        <% else %>
          <%= render 'relationship_form', object: @user, style: "" if logged_in? %>
        <% end %>
      </span>
    </h1>
    <p><strong><%= @user.name %></strong></p>
    <p>
       <span class="stats"><%= pluralize(@user.posts.count, 'post') %></span>
       <span class="stats"><%= link_to pluralize(@user.followers.count, 'follower'), followers_user_path(@user) %></span>
       <span class="stats"><%= link_to "#{@user.following.count} following", following_user_path(@user) %></span>
    </p>
  </div>
</section>

<section>
  <% if @user.posts.any? %>
    <div class="album py-5 bg-light">
      <div class="container">
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
          <%= render @posts %>
        </div>
      </div>
    </div>
  <% end %>
<section>

<footer class="text-muted py-5">
  <div class="container">
    <p class="float-end mb-1">
      <a href="#">Back to top</a>
    </p>
    <p class="mb-1">&copy; Instagram</p>
  </div>
</footer>