config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  get    '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users
  resources :posts, except: [:index]
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :relationships, only: [:create, :destroy]
  resources :posts do
    resources :comments, only: [:create]
  end
  resources :posts do
    resources :likes, only: [:create]
    member do
      get :likes
    end
  end
end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div class="error-messages">
      <%= object.errors.full_messages.to_sentence %>
  </div>
<% end %>

app/views/shared/_flash_messages.html.erb
<% unless move_flash_messages?  %>
  <div class="container">
    <% flash.each do |message_type, message| %>
      <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
    <% end %>
  </div>
<% end %>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-expand-lg fixed-top navbar-light bg-light" aria-label="Main navigation">
  <div class="container">
    <a href="/" class="navbar-brand">
      <span class="logo h3">Instagram</span>
    </a>
    <div class="d-flex offcanvas-collapse">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item"><%= link_to "Home", root_path, class: "nav-link" %></li>
        <% if logged_in? %>
          <li class="nav-item"><%= link_to "Post", new_post_path, class: "nav-link" %></li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-bs-toggle="dropdown" aria-expanded="false">Account</a>
            <ul class="dropdown-menu" aria-labelledby="dropdown01">
              <li><%= link_to "Profile", current_user, class: "dropdown-item" %></li>
              <li><%= link_to "Users", users_path, class: "dropdown-item" %></li>
              <li><%= link_to "Settings", edit_user_path(current_user), class: "dropdown-item" %></li>
              <li><hr class="dropdown-divider"></li>
              <li><%= link_to "Log out", logout_path, data: { "turbo-method": :delete }, class: "dropdown-item" %></li>
            </ul>
          </li>
        <% else %>
          <li class="nav-item"><%= link_to "Log in", login_path, class: "nav-link" %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>