config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  get    '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users
  resources :posts, except: [:index]
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :relationships, only: [:create, :destroy]
  resources :posts do
    resources :comments, only: [:create]
  end
  resources :posts do
    resources :likes, only: [:create]
    member do
      get :likes
    end
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  delegate :username, to: :user
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_one_attached :image
  default_scope -> { order(created_at: :desc) }
  validates :user_id, presence: true
  validates :caption, length: { maximum: 2200 }
  validates :image, content_type: { in: %w[image/jpeg image/png],
                                    message: "must be in jpeg or png format" },
                            size: { less_than: 30.megabytes,
                                    message:   "must be less than 30MB" }

  def show_large_image
    image.variant(resize_to_limit: [700, 700])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :logged_in_user, only: [:new, :create, :edit, :update, :destroy, :likes]
  before_action :correct_user, only: [:edit, :update, :destroy]

  def show
    @post = Post.find(params[:id])
    @comment = @post.comments.build
  end

  def new
    @post = current_user.posts.build
  end

  def edit
  end

  def create
    @post = current_user.posts.build(post_params)
    @post.image.attach(params[:post][:image])
    if @post.save
      flash[:success] = "Your post has been shared"
      redirect_to current_user
    else
      render 'new', status: :unprocessable_entity
    end
  end

  def update
    if @post.update(post_params)
      flash[:success] = "Your post has been updated"
      redirect_to current_user
    else
      render 'edit', status: :unprocessable_entity
    end
  end

  def destroy
    @post.destroy
    flash[:success] = "Your post has been deleted"
    redirect_to current_user, status: :see_other
  end

  def likes
    @likes = Post.find(params[:id]).likes
    render 'likes'
  end

  private

  def post_params
    params.require(:post).permit(:caption, :image)
  end

  def correct_user
    @post = current_user.posts.find_by(id: params[:id])
    redirect_to root_url if @post.nil?
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_comment_form.html.erb
<%= form_with(model: @comment, url: post_comments_path(object), local: true) do |f| %>
  <%= f.text_field :content, placeholder: "Write a comment...", required: true%>
  <%= f.submit "Post comment", class: "btn-sm btn-primary comment-btn" %>
<% end %>

app/views/posts/_likes_info.html.erb
<p>
  <span class="heart-icon"><%= link_to fa_icon("heart"), post_likes_path(object),
        data: { "turbo-method": :post } %></span>
  <span class="likes-count"><%= link_to(pluralize(object.likes.count, 'like'), likes_post_path(object) ) %></span>
</p>

app/views/posts/_post.html.erb
<div class="col">
  <div class="card-body gallery-thumbs">
    <% if post.image.attached? %>
      <%= link_to image_tag(post.image, size: "325x325"), post %>
    <% else %>
      <%= link_to image_tag(""), post %>
    <% end %>

    <div class="thumb-stats">
      <div class="thumb-text">
        <span><%= fa_icon("heart") %> <%= post.likes.count %></span>
        <span class=><%= fa_icon("comment") %> <%= post.comments.count %></span>
      </div>
    </div>
  </div>
</div>

app/views/posts/_post_form.html.erb
<div class="form-card">
  <div class="card">
    <div class="card-body">
      <h6 class="mb-3 mt-2 text-center"><%= yield(:subtitle) %></h6>
      <p class="text-muted"><%= fa_icon("user-circle") %>
        <%= current_user.username %>
      <p>
      <%= form_with(model: @post, local: true) do |f| %>
        <%= f.file_field :image, accept: "image/jpeg,image/png", required: true %>
        <%= f.text_area :caption, placeholder: "Write a caption...", class: "form-control", rows:9 %>
        <%= f.submit yield(:button), class: "w-100 btn btn-primary" %>
        <%= render 'shared/error_messages', object: f.object %>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/_post_info.html.erb
<span class='user-link'><%= fa_icon("user-circle") %>
                        <%= link_to object.username, object.user %>
</span>
<span class="text-muted"><%= object.caption %></span>

app/views/posts/edit.html.erb
<% provide(:subtitle, "Edit post") %>
<% provide(:button, "Update Post") %>

<%= render 'post_form' %>

app/views/posts/feed.html.erb
<div class="users-card">
  <% if @feed_posts.any? %>
    <% @feed_posts.each do |post| %>
      <div class="col">
        <div class="card mb-5 card-body feed">
          <span class='mb-3 user-link'><%= fa_icon("user-circle") %>
                                  <%= link_to post.username, post.user %>
          </span>
          <% if post.image.attached? %>
            <%= link_to image_tag(post.image), post %>
          <% else %>
            <%= link_to image_tag(""), post %>
          <% end %>

          <p class="mt-2">
            <%= render 'posts/likes_info', { object: post } %>
            <%= render 'posts/post_info', { object: post } %>
          </p>
          <%= render 'posts/comment_form', { object: post } %>
        </div>
      </div>
    <% end %>
  <% else %>
    <div class="text-center">
      <%= link_to "Follow a user to see your feed", users_path, class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/posts/likes.html.erb
<div class="users-card">
  <div class="card">
    <div class="card-body">
      <h5 class="relationship-title text-center mb-3">Likes</h5>
      <% if @likes.any? %>
        <hr class="divider">
        <ul class="users">
          <% @likes.each do |like| %>
            <%= render like.user, object: like.user, style: "follow-button"%>
          <% end %>
        </ul>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<% provide(:subtitle, "Create new post") %>
<% provide(:button, "Post") %>

<%= render 'post_form' %>

app/views/posts/show.html.erb
<div class="back-button">
  <%= link_to 'Back', request.referrer == root_url ? :back : @post.user %>
</div>

<div class="show-card">
  <div class="container">
    <div class= "card">
      <div class="card-body p-0">
        <div class="row">
          <div class="col col-md-auto">
            <% if @post.image.attached? %>
              <span class="picture"><%= image_tag(@post.show_large_image)%></span>
            <% else %>
               <%= image_tag("")%>
            <% end %>
          </div>
          <div class="col mt-2">
            <% if current_user?(@post.user) %>
              <span class="post-links"><%= link_to 'edit',edit_post_path(@post)%> |
                <%= link_to 'delete', @post, class: "delete-btn",
                data: { "turbo-method": :delete, "turbo_confirm": 'Are you sure?' } %>
              </span>
            <% else %>
              <span class='user-link'><%= fa_icon("user-circle") %>
                                      <%= link_to @post.user.username, @post.user %>
              </span>
              <span><%= render 'users/relationship_form', { object: @post.user, style: "btn-sm mt-2" } if logged_in? %></span>
            <% end %>
            <hr>
            <p>
              <%= render 'posts/post_info', { object: @post } %>
            </p>

            <% if @post.comments.any? %>
              <%= render @post.comments %>
            <% end %>
          </div>

          <div class="row align-items-end fixed">
            <div class="col-7"></div>
            <div class="col-5">
              <div class="comment-form">
                <%= render 'posts/likes_info', { object: @post } %>
                <%= render 'posts/comment_form', { object: @post } %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>